### ISSUE TITLE
Crash on dimensions below 0

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/krusgen#1]
Krusgen crashes when passed dimensions are below zero.
Affects both `-x` and `-y` options.

![image](https://cloud.githubusercontent.com/assets/6173262/25307938/735e48bc-27aa-11e7-95e3-9be210d14bf6.png)

**Comment by mazaczysko** [comment]
Please be more patient next time :bangbang:

**Comment by mazaczysko** [comment]
Thank you.
