### ISSUE TITLE
krusgen can easily crash PC if right dimensions are provided

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/krusgen#10]
Try running `krusgen -x 65536 -y 1` and wait a couple of seconds.

This is the most likely outcome:
![Screenshot from 2019-03-10 19-08-30](https://user-images.githubusercontent.com/6173262/54089319-2224af00-4368-11e9-93f3-0354edba1b63.png)

I had to terminate the program in order to take this screenshot - otherwise my computer would freeze.

**Comment by Jacajack** [comment]
bump

EDIT: this works with negative values for -x and -y too

**Comment by mazaczysko** [comment]
I have fixed this issue in [8d1a1e9](https://github.com/mazaczysko/krusgen/commit/8d1a1e9364ad2bb5c91397c491fed05ad732f823). However it fixes the problem only for improper (even and not-positive) dimensions. I am working on getting it to work properly, similar problem, for proper dimensions, is mentioned in #11 issue. If you want to stay up-to-date please follow #11 issue thread.
