### ISSUE TITLE
Values for options can be provided multiple times

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/krusgen#15]
For example, this invocation produces only one file named `c`:
```$ ./krusgen -x 15 -y 15 -w 3 -t a -t b -t c```

**Comment by mazaczysko** [comment]
In upcoming commit I'll add warnings to indicate that flags were used multiple times and that last declared value will be assigned.
I will consider adding multiple files output in the future. Thanks for bringing my attention to such an issue.
