### ISSUE TITLE
Crash on not-permitted file operations

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/krusgen#2]
Krusgen crashes when user tries to pick output file he/she doesn't have rights to modify create. Problem affects both `-b` and `-t` options, creating and modifying files.
This behavior is likely caused by missing `exit()` call on lines [95](https://github.com/mazaczysko/krusgen/blob/master/src/krusgen.c#L95) and [111](https://github.com/mazaczysko/krusgen/blob/master/src/krusgen.c#L111).

![image](https://cloud.githubusercontent.com/assets/6173262/25307990/6c2389e4-27ab-11e7-91a6-654d5e060e27.png)

**Comment by mazaczysko** [comment]
Always...

**Comment by Jacajack** [comment]
Affects too long names too.
![image](https://cloud.githubusercontent.com/assets/6173262/25308106/efd4de94-27ad-11e7-8a26-15e85fe9c919.png)

**Comment by Jacajack** [comment]
@mazaczysko Bug still exists in `1.2-41+3e778e8+201704271902~ubuntu14.04.1`. (Generally the `1.2` version)
Missing `exit()` call on line [222](https://github.com/mazaczysko/krusgen/blob/master/src/krusgen.c#L222)  may likely be the source of the problem.
