### ISSUE TITLE
Crash caused by large dimensions

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/krusgen#3]
Krusgen crashes when given maze dimensions are too big. Affects both `-x` and `-y` options.
This behavior is likely caused by ignoring `calloc` errors returned by [`mazeInit`](https://github.com/mazaczysko/krusgen/blob/master/src/maze.c#L35) routine.
Also, some reasonable upper maze size limit should be introduced.

![image](https://cloud.githubusercontent.com/assets/6173262/25308033/a9e69716-27ac-11e7-84fa-e2c9d4b5b31b.png)

**Comment by mazaczysko** [comment]
Thank you.
