### ISSUE TITLE
Empty output files

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/krusgen#4]
When `-t <filename> -h` are both passed to Krusgen in that specific order, the output file is created before the help message appears. The output file contains no data, which is an unusual and unexpected behavior. This bug affects `-b` option too. 
![image](https://cloud.githubusercontent.com/assets/6173262/25308353/65d775b2-27b2-11e7-8a31-8af7beebc739.png)

Things get even worse when both `-b` and `-t` options are used. Then program doesn't even output proper error message (`krusgen: cannot export to .bmp and .txt files at once`) and both files are created.
![image](https://cloud.githubusercontent.com/assets/6173262/25308388/5923a326-27b3-11e7-9f3e-4a87cd9738c8.png)

**Comment by mazaczysko** [comment]
Thank you.
