### ISSUE TITLE
Invalid frame argument handling

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/krusgen#6]
There seems to be a problem with `FLAG_FRAME` flag handling. Logical operator is used instead of bitwise one.

![screenshot from 2018-09-30 00-44-43](https://user-images.githubusercontent.com/6173262/46251103-0b3d7080-c44a-11e8-9f93-1aa61ec39f2c.png)

Related code fragment:
https://github.com/mazaczysko/krusgen/blob/8478f0bbb0b319d1a82eee06d20d40a6d2fa38c2/src/maze.c#L59-L60

**Comment by mazaczysko** [comment]
Thank you

**Comment by mazaczysko** [comment]
Thank you.
