### ISSUE TITLE
Identical mazes are generated

### ISSUE THREAD

**Issue by Jacajack** [mazaczysko/krusgen#9]
If I want to generate many labyrinths using a bash for loop, all of them are identical:
```bash
for i in {1..10}; do ./krusgen > "out/$i.txt"; done
```

This makes the program unusable in cases where more than one maze is needed. The program doesn't support multiple files output and produces unsatisfactory results when it's repeatedly called instead.

**Comment by mazaczysko** [comment]
Of course it can be annoying when you need to generate more than one maze. I am going to correct this issue in upcoming commit. I would consider support multiple files output in upcoming revisions.
